name: Scheduled Deploy

on:
  schedule:
    # Se ejecuta a las 5:00 AM UTC (Medianoche en Lima/Bogotá)
    - cron: '0 5 * * *'
  
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build site
        run: pnpm run build

      - name: Pushing to target repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist'
          destination-github-username: 'yamilayma'
          destination-repository-name: 'yamilayma.github.io'
          user-email: yamilaymadev@gmail.com
          target-branch: main